######################################################################
# Automatically generated by qmake (2.01a) mån aug 10 15:49:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . lib
INCLUDEPATH += . lib

# Input
HEADERS += lib/myphoneapi.h
SOURCES += main.cpp lib/myphoneapi.cpp
