######################################################################
# Automatically generated by qmake (2.01a) mån aug 10 15:37:42 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myphoneapi.h
SOURCES += myphoneapi.cpp
